// src/modules/recipes/pdf.js
// Uses Puppeteer to render HTML → PDF, same as Laravel's DomPDF blade template.
// Puppeteer is heavier than DomPDF but produces better output and needs no PHP.

import puppeteer from 'puppeteer';

/**
 * @param {object} recipe - Prisma recipe with user, ingredients, images
 * @param {string|null} imageData - base64 data URI of primary image
 * @returns {Buffer} PDF buffer
 */
export async function generateRecipePdf(recipe, imageData) {
  const html = buildHtml(recipe, imageData);

  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });

    const buffer = await page.pdf({
      format:            'A4',
      printBackground:   true,
      margin: { top: '20mm', right: '20mm', bottom: '20mm', left: '20mm' },
    });

    return Buffer.from(buffer);
  } finally {
    await browser.close();
  }
}

function buildHtml(recipe, imageData) {
  const ingredientRows = recipe.ingredients
    .map(ing => {
      const qty  = ing.quantity ? `${ing.quantity}` : '';
      const unit = ing.unit ?? '';
      return `<tr><td>${qty} ${unit}</td><td>${ing.name}</td></tr>`;
    })
    .join('');

  const stepsHtml = (Array.isArray(recipe.steps) ? recipe.steps : [])
    .map((step, i) => `<li><strong>Step ${i + 1}:</strong> ${step}</li>`)
    .join('');

  const imageSrc = imageData
    ? `<img src="${imageData}" alt="${recipe.title}" class="recipe-image" />`
    : '';

  const nutri = recipe.nutritionalInfo ?? {};
  const nutriHtml = Object.keys(nutri).length
    ? `<div class="section">
        <h3>Nutritional Info</h3>
        <table class="nutri-table">
          ${Object.entries(nutri).map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join('')}
        </table>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    body { font-family: Georgia, serif; color: #222; margin: 0; padding: 0; }
    h1   { font-size: 28px; margin-bottom: 4px; }
    h3   { font-size: 16px; border-bottom: 1px solid #ccc; padding-bottom: 4px; margin-top: 24px; }
    .meta { color: #666; font-size: 13px; margin-bottom: 16px; }
    .recipe-image { width: 100%; max-height: 280px; object-fit: cover; border-radius: 6px; margin-bottom: 16px; }
    table  { width: 100%; border-collapse: collapse; font-size: 14px; }
    td     { padding: 5px 8px; border-bottom: 1px solid #eee; }
    td:first-child { width: 30%; color: #555; }
    ol, ul { padding-left: 20px; }
    li     { margin-bottom: 8px; font-size: 14px; line-height: 1.6; }
    .nutri-table td:first-child { text-transform: capitalize; }
    .footer { margin-top: 32px; font-size: 11px; color: #aaa; text-align: center; }
    .section { margin-top: 20px; }
  </style>
</head>
<body>
  ${imageSrc}
  <h1>${recipe.title}</h1>
  <div class="meta">
    By ${recipe.user.name} &nbsp;·&nbsp;
    ${recipe.category} &nbsp;·&nbsp;
    ${recipe.difficulty} &nbsp;·&nbsp;
    Prep: ${recipe.prepTime} min &nbsp;·&nbsp;
    Cook: ${recipe.cookTime} min &nbsp;·&nbsp;
    Serves: ${recipe.servings ?? 4}
  </div>

  <p>${recipe.description}</p>

  <div class="section">
    <h3>Ingredients</h3>
    <table>${ingredientRows}</table>
  </div>

  <div class="section">
    <h3>Instructions</h3>
    <ol>${stepsHtml}</ol>
  </div>

  ${nutriHtml}

  <div class="footer">Generated by recipe-sharing-platform.com</div>
</body>
</html>`;
}
